"""Add memory models

Revision ID: d5d4c0b646ef
Revises: 16c67a8e39a0
Create Date: 2026-07-21 22:16:56.239961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d4c0b646ef'
down_revision: Union[str, Sequence[str], None] = '16c67a8e39a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_memory_key', 'project_memory', ['project_id', 'key'], unique=True)
    op.create_index('ix_project_memory_project_id', 'project_memory', ['project_id'], unique=False)
    op.create_table('experience_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('source_project_id', sa.String(), nullable=True),
    sa.Column('source_execution_id', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experience_memory_created_at', 'experience_memory', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_experience_memory_created_at', table_name='experience_memory')
    op.drop_table('experience_memory')
    op.drop_index('ix_project_memory_project_id', table_name='project_memory')
    op.drop_index('ix_project_memory_key', table_name='project_memory')
    op.drop_table('project_memory')
    # ### end Alembic commands ###
